name: Publish to NPM
on:
  push:
    branches: ["develop"]
  workflow_call:

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    secrets:
      # this secret is a token generated here: https://www.npmjs.com/settings/oeed/tokens/granular-access-tokens/new
      # it does expire after a year
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      # based on the instructions given by werift's maintainers: https://github.com/shinyoshiaki/werift-webrtc/issues/251
      - uses: actions/checkout@v2
      - name: root dependencies
        run: npm install
      - name: webrtc dependencies
        run: npm install
        working-directory: ./packages/webrtc
      - name: version patch
        run: npm version patch
        working-directory: ./packages/webrtc
      - name: build
        run: npm run build
        working-directory: ./packages/webrtc
      - name: npm login
        run: npm set "//registry.npmjs.org/:_authToken" ${{ secrets.NPM_TOKEN }}
      - name: publish
        run: npm publish
        working-directory: ./packages/webrtc
      - name: commit version patch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "$(npm list --depth 1 @oeed/werift | grep "@oeed/werift" |  grep -o "\d*\.\d*\.\d*")"  
          git push
